source = ~/.config/hypr/utils/colors.conf

# Workspace Rules
workspace = special:terminalScratchpad, on-created-empty:ghostty,gapsout:15
workspace = special:workBrowserScratchpad, on-created-empty:qutebrowser, gapsout:30, gapsin:5

workspace = 1, monitor:$mainMonitor, default:true,persistent:true
workspace = 2, monitor:$mainMonitor, default:true,persistent:true
workspace = 3, monitor:$mainMonitor, default:true,persistent:true
workspace = 4, monitor:$mainMonitor, default:true,persistent:true
workspace = 5, monitor:$mainMonitor, default:true,persistent:true
workspace = 6, monitor:$secondMonitor, default:true,persistent:true

# Window Rules

## Ignore maximize requests from apps
windowrule = suppress_event maximize, match:class .*

## Fix some dragging issues with XWayland
windowrule = no_focus on,match:class ^$,match:title ^$,match:xwayland 1,match:float 1,match:fullscreen 0,match:pin 0

$activeOpacity = 0.6
$inactiveOpacity = 0.5
$fullscreenOpacity = 0.5

windowrule {
    name = OnFullscreen
    match:fullscreen = 1

    border_size = 5
    rounding = 1
    border_color = $error
}

windowrule {
    name = TerminalScratchpad
    enable = true
    match:workspace = special:terminalScratchpad
    opacity = $activeOpacity override $inactiveOpacity override $fullscreenOpacity override 
}

windowrule {
    name = Screensaver
    match:class = terminal-screensaver

    float = on
    center = on
    pin = on
    maximize = on
}

windowrule {
    name = FloatingPavucontrol
    match:class = org.pulseaudio.pavucontrol

    float = on
    center = on
    size = (monitor_w*0.5) (monitor_h*0.6)
}

windowrule {
    name = FloatingGnomeCalculator
    match:class = org.gnome.Calculator

    float = on
    center = on
    size = (monitor_w*0.5) (monitor_h*0.6)
}

windowrule {
    name = FloatingBluemanManager
    match:class = blueman-manager

    float = on
    center = on
    size = (monitor_w*0.5) (monitor_h*0.6)
}

windowrule {
    name = FloatingBitwarden
    match:class = Bitwarden

    float = on
    center = on
    size = (monitor_w*0.5) (monitor_h*0.6)
}


windowrule {
    name = FloatingKclock
    match:class = org.gnome.clocks

    float = on
    center = on
    size = (monitor_w*0.5) (monitor_h*0.6)
}

windowrule {
    name = FloatingKitty
    match:class = kitty

    float = on
    center = on
    size = (monitor_w*0.5) (monitor_h*0.6)
}

windowrule {
    name = FloatingAnki
    match:class = anki

    float = on
    center = on
    size = (monitor_w*0.6) (monitor_h*0.8)
}

windowrule {
    name = FloatingThunar
    match:class = thunar

    float = on
    center = on
    size = (monitor_w*0.6) (monitor_h*0.8)
}

windowrule {
    name = FloatingImageViewer
    match:class = Nsxiv

    float = on
    center = on
    size = (monitor_w*0.6) (monitor_h*0.8)
}

windowrule {
    name = FloatingNetworkMenu
    match:class = nm-connection-editor

    float = on
    center = on
    size = (monitor_w*0.6) (monitor_h*0.8)
}

windowrule {
    name = FloatingSharePicker
    match:class = hyprland-share-picker

    float = on
    center = on
    size = (monitor_w*0.6) (monitor_h*0.8)
}

windowrule {
    name = ExecQutebrowserAsGroup
    match:class = org.qutebrowser.qutebrowser

    group = set
}

windowrule {
    name = ExecObsStudioOnSpecificWorkspace
    match:class = com.obsproject.Studio

    workspace = 5
    no_initial_focus = on
}

windowrule {
    name = ExecMsTeamsOnLastWorkspace
    match:class = teams-for-linux

    workspace = 6
    no_initial_focus = on
}

windowrule {
    name = ExecDiscordOnLastWorkspace
    match:class = discord

    workspace = 6
    no_initial_focus = on
}

