## Monitors

monitor= $secondMonitor,preferred,auto,1
monitor= $mainMonitor,preferred,auto,1
monitor = , preferred, auto, 1, mirror, $mainMonitor # Mirrors main monitor to any unspecified output (comment if secondMonitor is not specified to prevent override)

## Defaults
$mainMonitor = eDP-1
$secondMonitor = 
$browser = librewolf --new-window
$terminal = ghostty
$fileManager = thunar
$emailClient = thunderbird
$waybarConfig = $XDG_CONFIG_HOME/waybar/config-laptop.jsonc
$menu = rofi -show drun

## Scripts
$clipboardHistory = $XDG_CONFIG_HOME/scripts/menu/clipboard-history.sh
$refreshWaybar = $XDG_CONFIG_HOME/scripts/waybar_refresh.sh
$toggleWaybar = $XDG_CONFIG_HOME/scripts/waybar_toggle.sh
$audioSwitcherScript = $XDG_CONFIG_HOME/scripts/menu/audio-switcher.sh
$reloadConfigScript = $XDG_CONFIG_HOME/hypr/scripts/reload-config.sh
$screenshotMenu = $XDG_CONFIG_HOME/scripts/menu/screenshot-menu.sh
$runScripts = $XDG_BIN_HOME/run-scripts.sh

## Sound Effects
$soundFx1 = $XDG_CONFIG_HOME/hypr/utils/sound_fx/disco_elysium_fx/physique.mp3
$soundFx2 = $XDG_CONFIG_HOME/hypr/utils/sound_fx/disco_elysium_fx/psyche.mp3
$soundFx3 = $XDG_CONFIG_HOME/hypr/utils/sound_fx/disco_elysium_fx/motorics.mp3
$soundFx4 = $XDG_CONFIG_HOME/hypr/utils/sound_fx/disco_elysium_fx/intellect.mp3

## Environment Variables
env = XCURSOR_SIZE,18
env = HYPRCURSOR_SIZE,18
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_QPA_PLATFORMTHEME,qt5ct
