# System utilities(excluding drivers)
SYSTEM_UTILS=(
  bat
  bc
  brightnessctl
  btop
  cliphist
  curl
  dunst
  fastfetch
  fd
  firefox
  foot
  fzf
  ghostty
  hypridle
  hyprlock
  hyprpaper
  hyprshot
  hyprsunset
  imagemagick
  jq
  kclock
  kitty
  librewolf-bin
  man
  matugen
  mpv
  mullvad-vpn-bin
  neovim
  nsxiv
  nwg-look
  obsidian
  okular
  openrgb
  pacman-contrib
  pavucontrol
  ripgrep
  rofi
  rsync
  sed
  starship
  stow
  tealdeer
  tesseract
  thunar
  tmux
  ungoogled-chromium-bin
  unzip
  vi
  vim
  waybar
  wget
  wlogout
  xorg-xrdb
  yt-dlp
  zip
  zoxide
  zsh
  zsh-syntax-highlighting
)

DEV_TOOLS=(
  bruno-bin
  docker
  git
  go
  lazydocker
  npm
  openbsd-netcat
  opencode-bin
  postgresql
  python-adblock
  qutebrowser
  typescript
)

EXTRA=(
   libreoffice-still
   obs-studio
   obs-cmd
)
# Fonts
FONTS=(
  noto-fonts
  noto-fonts-cjk
  noto-fonts-emoji
  ttc-iosevka
  ttf-bitstream-vera
  ttf-cascadia-code-nerd
  ttf-firacode-nerd
  ttf-jetbrains-mono-nerd
  ttf-nerd-fonts-symbols-common
  woff2-font-awesome
)

# Services to enable
SERVICES=(
  NetworkManager.service
)

# Services to enable
USER_SERVICES=(
  openrgb.service
  package-updates.timer
)

